// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function isPlaceholderDatabaseUrl(connectionString: string): boolean {
  return (
    connectionString.includes("...") ||
    connectionString.includes("ep-xxx") ||
    connectionString.includes("@host:")
  );
}

function normalizeDatabaseUrl(
  connectionString: string | undefined,
): string | undefined {
  if (!connectionString) {
    return undefined;
  }

  if (isPlaceholderDatabaseUrl(connectionString)) {
    return undefined;
  }

  try {
    const url = new URL(connectionString);
    if (
      url.protocol === "postgresql:" &&
      url.hostname.endsWith(".neon.tech")
    ) {
      const sslMode = url.searchParams.get("sslmode");
      if (!sslMode || ["prefer", "require", "verify-ca"].includes(sslMode)) {
        url.searchParams.set("sslmode", "verify-full");
      }
      return url.toString();
    }
  } catch {
    return connectionString;
  }

  return connectionString;
}

const migrationDatabaseUrl =
  normalizeDatabaseUrl(process.env["PRISMA_MIGRATE_DATABASE_URL"]) ||
  normalizeDatabaseUrl(process.env["DIRECT_URL"]) ||
  normalizeDatabaseUrl(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
