// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function normalizeDatabaseUrl(connectionString: string | undefined): string | undefined {
  if (!connectionString) {
    return undefined;
  }

  try {
    const url = new URL(connectionString);
    if (
      url.protocol === "postgresql:" &&
      url.hostname.endsWith(".neon.tech") &&
      !url.searchParams.has("sslmode")
    ) {
      url.searchParams.set("sslmode", "require");
      return url.toString();
    }
  } catch {
    return connectionString;
  }

  return connectionString;
}

const migrationDatabaseUrl =
  normalizeDatabaseUrl(process.env["PRISMA_MIGRATE_DATABASE_URL"]) ||
  normalizeDatabaseUrl(process.env["DIRECT_URL"]) ||
  normalizeDatabaseUrl(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
