import { ApplicationConfig, LOCALE_ID, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { IMAGE_CONFIG, registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Apple,
  Archive,
  BadgeCheck,
  Banknote,
  Bell,
  BellOff,
  Bookmark,
  BriefcaseBusiness,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Circle,
  CircleDollarSign,
  CircleX,
  Clock3,
  Clipboard,
  CornerDownLeft,
  Eye,
  FileUp,
  FileText,
  Flame,
  Gavel,
  Heart,
  HeartPlus,
  HeartPulse,
  Handshake,
  Info,
  ImagePlus,
  GitFork,
  Globe,
  Globe2,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  Lock,
  LockKeyhole,
  LocateFixed,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Maximize2,
  MessageCircle,
  Minimize2,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Paintbrush,
  Pencil,
  Phone,
  Plus,
  Power,
  Receipt,
  RotateCcw,
  Scale,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Settings,
  SlidersHorizontal,
  Star,
  Smartphone,
  Stethoscope,
  Trash2,
  TriangleAlert,
  UploadCloud,
  UserRoundCog,
  Users,
  Video,
  WalletCards,
  Wrench,
  X,
  Zap,
  LucideAngularModule,
} from 'lucide-angular';
// Register French locale
registerLocaleData(localeFr);


export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(), 
    { provide: LOCALE_ID, useValue: 'fr-FR' },
    provideRouter(routes),
    provideHttpClient(withInterceptors([jwtInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUpRight,
        Apple,
        Archive,
        BadgeCheck,
        Banknote,
        Bell,
        BellOff,
        Bookmark,
        BriefcaseBusiness,
        Calendar,
        CalendarCheck,
        CalendarDays,
        Camera,
        ChartNoAxesCombined,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        Clock,
        Circle,
        CircleDollarSign,
        CircleX,
        Clock3,
        Clipboard,
        CornerDownLeft,
        Eye,
        FileUp,
        FileText,
        Flame,
        Gavel,
        Heart,
        HeartPlus,
        HeartPulse,
        Handshake,
        Info,
        ImagePlus,
        GitFork,
        Globe,
        Globe2,
        LayoutDashboard,
        LoaderCircle,
        LogOut,
        Lock,
        LockKeyhole,
        LocateFixed,
        Mail,
        Map,
        MapPin,
        MapPinned,
        Maximize2,
        MessageCircle,
        Minimize2,
        Minus,
        MoreHorizontal,
        MoreVertical,
        Paperclip,
        Paintbrush,
        Pencil,
        Phone,
        Plus,
        Power,
        Receipt,
        RotateCcw,
        Scale,
        Search,
        Send,
        Share2,
        ShieldCheck,
        Settings,
        SlidersHorizontal,
        Star,
        Smartphone,
        Stethoscope,
        Trash2,
        TriangleAlert,
        UploadCloud,
        UserRoundCog,
        Users,
        Video,
        WalletCards,
        Wrench,
        X,
        Zap,
      }),
    ),
    {
      provide: IMAGE_CONFIG,
      useValue: {
        disableImageSizeWarning: true, 
        disableImageLazyLoadWarning: true
      }
    }
  ],
};
