import { ApplicationConfig, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { IMAGE_CONFIG, registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Bell,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CircleX,
  Clock3,
  Clipboard,
  Heart,
  HeartPlus,
  HeartPulse,
  Handshake,
  LogOut,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  Power,
  RotateCcw,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Settings,
  SlidersHorizontal,
  Star,
  Trash2,
  TriangleAlert,
  Users,
  Video,
  WalletCards,
  Wrench,
  X,
  LucideAngularModule,
} from 'lucide-angular';
// Register French locale
registerLocaleData(localeFr);


export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(), 
    provideRouter(routes),
    provideHttpClient(withInterceptors([jwtInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUpRight,
        Banknote,
        Bell,
        CalendarDays,
        Camera,
        Check,
        ChevronDown,
        ChevronRight,
        CircleDollarSign,
        CircleX,
        Clock3,
        Clipboard,
        Heart,
        HeartPlus,
        HeartPulse,
        Handshake,
        LogOut,
        LockKeyhole,
        Mail,
        Map,
        MapPin,
        MessageCircle,
        MoreHorizontal,
        MoreVertical,
        Pencil,
        Phone,
        Plus,
        Power,
        RotateCcw,
        Search,
        Send,
        Share2,
        ShieldCheck,
        Settings,
        SlidersHorizontal,
        Star,
        Trash2,
        TriangleAlert,
        Users,
        Video,
        WalletCards,
        Wrench,
        X,
      }),
    ),
    {
      provide: IMAGE_CONFIG,
      useValue: {
        disableImageSizeWarning: true, 
        disableImageLazyLoadWarning: true
      }
    }
  ],
};
