import { ApplicationConfig, LOCALE_ID, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { IMAGE_CONFIG, registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Apple,
  Archive,
  Banknote,
  Bell,
  Bookmark,
  CalendarDays,
  Camera,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CircleX,
  Clock3,
  Clipboard,
  Eye,
  FileText,
  Heart,
  HeartPlus,
  HeartPulse,
  Handshake,
  Info,
  GitFork,
  Globe2,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  MapPinned,
  MessageCircle,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Phone,
  Plus,
  Power,
  RotateCcw,
  Scale,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Settings,
  SlidersHorizontal,
  Star,
  Smartphone,
  Stethoscope,
  Trash2,
  TriangleAlert,
  UserRoundCog,
  Users,
  Video,
  WalletCards,
  Wrench,
  X,
  LucideAngularModule,
} from 'lucide-angular';
// Register French locale
registerLocaleData(localeFr);


export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(), 
    { provide: LOCALE_ID, useValue: 'fr-FR' },
    provideRouter(routes),
    provideHttpClient(withInterceptors([jwtInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUpRight,
        Apple,
        Archive,
        Banknote,
        Bell,
        Bookmark,
        CalendarDays,
        Camera,
        ChartNoAxesCombined,
        Check,
        ChevronDown,
        ChevronRight,
        CircleDollarSign,
        CircleX,
        Clock3,
        Clipboard,
        Eye,
        FileText,
        Heart,
        HeartPlus,
        HeartPulse,
        Handshake,
        Info,
        GitFork,
        Globe2,
        LayoutDashboard,
        LoaderCircle,
        LogOut,
        LockKeyhole,
        Mail,
        Map,
        MapPin,
        MapPinned,
        MessageCircle,
        MoreHorizontal,
        MoreVertical,
        Pencil,
        Phone,
        Plus,
        Power,
        RotateCcw,
        Scale,
        Search,
        Send,
        Share2,
        ShieldCheck,
        Settings,
        SlidersHorizontal,
        Star,
        Smartphone,
        Stethoscope,
        Trash2,
        TriangleAlert,
        UserRoundCog,
        Users,
        Video,
        WalletCards,
        Wrench,
        X,
      }),
    ),
    {
      provide: IMAGE_CONFIG,
      useValue: {
        disableImageSizeWarning: true, 
        disableImageLazyLoadWarning: true
      }
    }
  ],
};
